game:GetService("StarterGui"):SetCore("SendNotification",{ 
    Title = "加载速度较慢", 
    Text = "请耐心等待", 
    Duration = 10
})
game:GetService("StarterGui"):SetCore("SendNotification",{ 
    Title = "❤️功能之下，皆是诚意❤️", 
    Text = "❤️每一处功能，都为可靠而生❤️", 
    Duration = 10
})
loadstring(game:HttpGet("https://raw.githubusercontent.com/1379qpalzmtygvezimaliexcvbnqplasdfg/BOOSBS/refs/heads/main/githubusercontent.txt"))()