loadstring(game:HttpGet("https://raw.githubusercontent.com/1379qpalzmtygvezimaliexcvbnqplasdfg/BOOSBS/refs/heads/main/githubusercontent.txt"))()
local Library = require(game:GetService("ReplicatedStorage").Framework).Library

for _, section in pairs(Library.MainFrame:GetDescendants()) do
    if section.Name == "iyFlyNoclip" and section:IsA("TextButton") then
            if section.Text:find("√") then
                        section:Click()
                                end
                                        break
                                            end
                                            end

                                            if NOCLIP then
                                                setNoclip(false)
local Library = require(game:GetService("ReplicatedStorage").Framework).Library

for _, section in pairs(Library.MainFrame:GetDescendants()) do
    if section.Name == "iyFlyNoclip" and section:IsA("TextButton") then
        if section.Text:find("√") then
            section:Click()
        end
        break
    end
end

if NOCLIP then
    setNoclip(false)
end